//Generated by S.Leo Matthew
//using "orion generate routes"

Router.route('/admin', function () {
  this.render('adminLogin');
});
Router.route('/admin/dashboard', function() {
  this.render('dashBoard');
});
Router.route('/admin/posts', function() {
  this.render('posts');
});
