//Generated by S.Leo Matthew
//using "orion generate routes"

Router.route('/admin', function () {
  this.render('admin');
});
Router.route('/Dashboard', function() {
  this.render('dashBoard');
});
Router.route('/Posts', function() {
  this.render('post');
});
